/**
 * This file is auto-generated by the Triplit CLI for migration 1691946305021.
 * You should not edit this file directly instead run migrations to update.
 */

import { Migration, CollectionRules } from "@triplit/db";
import migration_1691946305021 from "./migrations/1691946305021_init.json";
import { Schema as S } from "@triplit/client";
export const migrations = [migration_1691946305021 as Migration];
const schema = {
  answers: {
    attributes: S.Schema({
      pick: S.number(),
      questionId: S.string(),
      userId: S.string(),
    }),
    rules: {
      read: [
        {
          description: "Allow users to read answers",
          filter: [["userId", "=", "$SESSION_USER_ID"]],
        },
      ],
    } as CollectionRules<any>,
  },
};
export type Schema = typeof schema;
